# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='websitephoto_link',
            new_name='website_photo_link',
        ),
        migrations.AddField(
            model_name='event',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
